name: sanggar_mulya_bhakti
description: Aplikasi resmi Sanggar Mulya Bhakti - Pelestarian Budaya Tari Indramayu
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0

  # HTTP
  http: ^1.2.0

  # State management
  provider: ^6.1.1

  # Storage
  shared_preferences: ^2.2.2

  # Image
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Fonts — otomatis download, tidak perlu file lokal
  google_fonts: ^6.1.0

  # Slider indicator
  smooth_page_indicator: ^1.1.0

  # Utils
  intl: ^0.19.0

flutter:
  uses-material-design: true

  # Hapus bagian fonts: di sini karena kita pakai GoogleFonts runtime
  # Tidak perlu file .ttf lokal