// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzwzWEljpLAVuB3hCCbpoA9haANsBRV7c',
    appId: '1:611713677810:web:0bf2192c8c208a0085936b',
    messagingSenderId: '611713677810',
    projectId: 'sanggar-mulya-bhakti',
    authDomain: 'sanggar-mulya-bhakti.firebaseapp.com',
    storageBucket: 'sanggar-mulya-bhakti.firebasestorage.app',
    measurementId: 'G-NGT4B1VQTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhwOBl3BgZunSPkOMXcImkVFKt4ltom8c',
    appId: '1:611713677810:android:53d7ebb23cda7dcf85936b',
    messagingSenderId: '611713677810',
    projectId: 'sanggar-mulya-bhakti',
    storageBucket: 'sanggar-mulya-bhakti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0RcB7TSjwa_ZbcelyDqXxM71Cu-lli9U',
    appId: '1:611713677810:ios:34e9a44a87c5f1f085936b',
    messagingSenderId: '611713677810',
    projectId: 'sanggar-mulya-bhakti',
    storageBucket: 'sanggar-mulya-bhakti.firebasestorage.app',
    iosClientId: '611713677810-mkrku08s0ohvmoghsehcm76f2j19t2ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanggarMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0RcB7TSjwa_ZbcelyDqXxM71Cu-lli9U',
    appId: '1:611713677810:ios:34e9a44a87c5f1f085936b',
    messagingSenderId: '611713677810',
    projectId: 'sanggar-mulya-bhakti',
    storageBucket: 'sanggar-mulya-bhakti.firebasestorage.app',
    iosClientId: '611713677810-mkrku08s0ohvmoghsehcm76f2j19t2ti.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanggarMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzwzWEljpLAVuB3hCCbpoA9haANsBRV7c',
    appId: '1:611713677810:web:2ac95fde1fb8a23285936b',
    messagingSenderId: '611713677810',
    projectId: 'sanggar-mulya-bhakti',
    authDomain: 'sanggar-mulya-bhakti.firebaseapp.com',
    storageBucket: 'sanggar-mulya-bhakti.firebasestorage.app',
    measurementId: 'G-JJXNTBJK1F',
  );
}
